name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore TrainMonitor.sln

      - name: Build
        run: dotnet build TrainMonitor.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test TrainMonitor.sln --no-build --configuration Release --verbosity normal

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./TrainMonitor
          file: ./TrainMonitor/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/trainmonitor:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/trainmonitor:${{ github.sha }}
